Add missing stdarg.h include
Fixes the following error on Fedora and openSUSE

      error: unknown type name ‘va_list’

Signed-off-by: gandharva <gandharva@gmx.de>
Signed-off-by: Joachim Nilsson <troglobit@gmail.com>